services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: dmp-editor-dev
    container_name: dmp-editor-dev
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    environment:
      - DMP_EDITOR_HOST=0.0.0.0
      - DMP_EDITOR_PORT=3000
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    command: [ "sleep", "infinity" ]
    init: true
    networks:
      - dmp-editor-network

volumes:
  node_modules: {}

networks:
  dmp-editor-network:
    name: dmp-editor-network
    external: true
