name: test

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  test:
    if: github.repository == 'NII-DG/dmp-editor'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci

      - id: lint
        run: npm run test:lint
        continue-on-error: true

      - id: typecheck
        run: npm run test:typecheck
        continue-on-error: true

      - id: smoketest
        run: npm run test:vitest
        continue-on-error: true

      - id: build
        run: npm run build
        continue-on-error: true

      - name: "Fail if any previous step failed"
        if: ${{ failure() || steps.lint.outcome == 'failure' || steps.typecheck.outcome == 'failure' || steps.smoketest.outcome == 'failure' || steps.build.outcome == 'failure' }}
        run: exit 1
